### ISSUE TITLE
HVAC mode loop

### ISSUE THREAD

**Issue by JariInc** [jethome-ru/hassio-component-smart-thermostat#11]
I'm running the latest master on the latest stable Home Assistant in a Docker container.

I have following configuration:
```yaml
- platform: smart_thermostat
  unique_id: ilp_pid_thermostat
  name: Ilmalämpöpumppu
  target_sensor: sensor.ruuvitag_c3_16_f6_6c_57_eb_temperature
  min_temp: 17
  max_temp: 23
  precision: 0.1
  heat_cool_disabled: true
  heater:
    - entity_id: climate.toshiba_arctic_25
      pid_params: 0.666, 0.005, 0.0
      min: 17
      max: 23
```

`climate.toshiba_arctic_25` attributes are:

```yaml
hvac_modes:
  - 'off'
  - heat_cool
  - cool
  - heat
min_temp: 17
max_temp: 30
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
friendly_name: Toshiba Arctic 25
supported_features: 9
current_temperature: 0
temperature: 18
fan_mode: high
```

When both smart_thermostat and the heater are off and I set heat mode from smart_thermostat it starts to loop between heat and heat_cool modes in the heater:

```
hass  | 2022-12-01 12:49:22.719 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.ilp_pid_thermostat: mode changed: off -> heat
hass  | 2022-12-01 12:49:22.720 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.ilp_pid_thermostat: Changed controllers HVAC action from idle to heating (cur: 19.37, target: 19.5, mode: heat)
hass  | 2022-12-01 12:49:22.720 DEBUG (MainThread) [custom_components.smart_thermostat.climate] climate.ilp_pid_thermostat: Starting heater_1, hvac_action: heating, (cur: 19.37, target: 19.5), running: False, working: True
hass  | 2022-12-01 12:49:22.721 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Trying to start controller, cur: 19.37, target: 19.5 
hass  | 2022-12-01 12:49:22.721 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Setup PID done. (params: Kp=0.666, Ki=0.005, Kd=0.0, current_output: 18.0, limits: (17.0, 23.0))
hass  | 2022-12-01 12:49:22.722 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Started controller, cur: 19.37, target: 19.5 
hass  | 2022-12-01 12:49:22.722 INFO (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Turning on climate climate.toshiba_arctic_25 (hvac_mode_changed)
hass  | 2022-12-01 12:49:22.723 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Setting HVAC mode to heat
hass  | 2022-12-01 12:49:23.022 INFO (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Turning on climate climate.toshiba_arctic_25 (control_entity_changed)
hass  | 2022-12-01 12:49:23.023 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Setting HVAC mode to heat
hass  | 2022-12-01 12:49:23.568 INFO (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Turning on climate climate.toshiba_arctic_25 (control_entity_changed)
hass  | 2022-12-01 12:49:23.570 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Setting HVAC mode to heat
hass  | 2022-12-01 12:49:24.261 INFO (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Turning on climate climate.toshiba_arctic_25 (control_entity_changed)
hass  | 2022-12-01 12:49:24.262 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Setting HVAC mode to heat
hass  | 2022-12-01 12:49:24.806 INFO (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Turning on climate climate.toshiba_arctic_25 (control_entity_changed)
hass  | 2022-12-01 12:49:24.807 DEBUG (MainThread) [custom_components.smart_thermostat.controllers] climate.ilp_pid_thermostat: heater_1 - Setting HVAC mode to heat
```

Only way to prevent this is to 

1. Set both off
2. Set heater to heat mode 
3. Set smart_thermostat to heat mode

Now the loop doesn't happen and PID works nicely.

I tried various combinations of heater, cooler and heat_cool_disabled. All of them ended in the loop.
