### ISSUE TITLE
Error on thermostat startup : object has no attribute '_PwmSwitchPidController__running'

### ISSUE THREAD

**Issue by marc-cizeron** [jethome-ru/hassio-component-smart-thermostat#7]
Hi, since the last update the thermostat doesn't work anymore.

When i try to start the thermostat i get this error :

```
Traceback (most recent call last):
  File "/config/custom_components/smart_thermostat/controllers.py", line 707, in _async_pwm_control
    if not self.__running:
AttributeError: 'PwmSwitchPidController' object has no attribute '_PwmSwitchPidController__running'
```

I have two configuration : 
1. one heat/cool behavior with tolerence (i.e no PID)
2. A second one with one heater with PID params (i'am trying to tune)

The error occur for the both configuration.

Did i mis something in the config ?

```
# https://github.com/jethome-ru/hassio-component-smart-thermostat
- platform: smart_thermostat
  name: Smart Fermentation Chamber
  heater: switch.tube_chauffant
  cooler: switch.frigo
  target_sensor: sensor.sonde_chambre_de_fermentation_temperature
  min_temp: 2
  max_temp: 35
  precision: 0.1
  heat_cool_cold_tolerance: 0.1
  heat_cool_hot_tolerance: 0.1

- platform: smart_thermostat
  name: Chambre Enora Smart Thermostat
  target_sensor: sensor.sonde_1_bureau_temperature
  min_temp: 14
  max_temp: 30
  precision: 0.1
  heater:
    - entity_id: switch.bedroom_2_heater
      inverted: true
      pid_params:
        - 1
        - 0
        - 0
      pwm_period: 00:15:00
```
