### ISSUE TITLE
using same switch/valve for heating and cooling

### ISSUE THREAD

**Issue by AnduriI** [jethome-ru/hassio-component-smart-thermostat#9]
Hey,

I hope someone can help. I have a underfloor heating capable of heating and cooling. In both cases I need to open the same valve. The hvac mode of the thermostat will be set by an automation reading the supply temperature of my heating system.
- is it possible to disable the `heat_cool` mode and only have `heat` and `cool` available?
- I have the problem that when activating the heating valve the thermostat also tries to close the cooling valve (in `heat` mode). As they are the same this results in a loop. Can I make it that it ignores all coolers completely?

```
  - platform: smart_thermostat
    name: "Thermostat Arbeitszimmer"
    target_sensor: sensor.temperatur_arbeitszimmer
    min_temp: 18
    max_temp: 28
    precision: 0.5
    heater:
      - entity_id: switch.heizungsventil_arbeitszimmer
    cooler:
      - entity_id: switch.heizungsventil_arbeitszimmer
```

Regards,
Anduril
